In [1]:
!pip install py-AutoClean
!pip install pydataset

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting py-AutoClean
  Downloading py-AutoClean-1.1.3.tar.gz (9.5 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.8/dist-packages (from py-AutoClean) (1.0.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from py-AutoClean) (1.21.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (from py-AutoClean) (1.3.5)
Collecting loguru
  Downloading loguru-0.6.0-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 2.5 MB/s
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas->py-AutoClean) (2022.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas->py-AutoClean) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas->py-AutoClean) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn->py-AutoClean) (3.1.0)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn->py-AutoClean) (1.7.3)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.8/dist-packages (from scikit-learn->py-AutoClean) (1.2.0)
Building wheels for collected packages: py-AutoClean
  Building wheel for py-AutoClean (setup.py) ... done
  Created wheel for py-AutoClean: filename=py_AutoClean-1.1.3-py3-none-any.whl size=10287 sha256=416f5bc229c593b7bc9305cbfdddcc5f956ecc3d14f392c6dffc845be2a172f7
  Stored in directory: /root/.cache/pip/wheels/ad/4f/67/954c8ee23fbd4bd1cf075d267714fcd98fd9ef7b2514be8954
Successfully built py-AutoClean
Installing collected packages: loguru, py-AutoClean
Successfully installed loguru-0.6.0 py-AutoClean-1.1.3
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pydataset
  Downloading pydataset-0.2.0.tar.gz (15.9 MB)
     |████████████████████████████████| 15.9 MB 780 kB/s
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (from pydataset) (1.3.5)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from pandas->pydataset) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas->pydataset) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas->pydataset) (2022.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas->pydataset) (1.15.0)
Building wheels for collected packages: pydataset
  Building wheel for pydataset (setup.py) ... done
  Created wheel for pydataset: filename=pydataset-0.2.0-py3-none-any.whl size=15939432 sha256=4f575a476701179c21b4838dcbff5277c1e67897987b605168e616106b15e7af
  Stored in directory: /root/.cache/pip/wheels/d7/e5/36/85d319586b4a405d001029d489102f526ce5546248c295932a
Successfully built pydataset
Installing collected packages: pydataset
Successfully installed pydataset-0.2.0

In [3]:
from pydataset import data

In [4]:
data()

        dataset_id                                             title
0    AirPassengers       Monthly Airline Passenger Numbers 1949-1960
1          BJsales                 Sales Data with Leading Indicator
2              BOD                         Biochemical Oxygen Demand
3     Formaldehyde                     Determination of Formaldehyde
4     HairEyeColor         Hair and Eye Color of Statistics Students
..             ...                                               ...
752        VerbAgg                  Verbal Aggression item responses
753           cake                 Breakage Angle of Chocolate Cakes
754           cbpp                 Contagious bovine pleuropneumonia
755    grouseticks  Data on red grouse ticks from Elston et al. 2001
756     sleepstudy       Reaction times in a sleep deprivation study

[757 rows x 2 columns]

In [16]:
df = data('BJsales')
df

     time  BJsales
1       1    200.1
2       2    199.5
3       3    199.4
4       4    198.9
5       5    199.0
6       6    200.2
7       7    198.6
8       8    200.0
9       9    200.3
10     10    201.2
11     11    201.6
12     12    201.5
13     13    201.5
14     14    203.5
15     15    204.9
16     16    207.1
17     17    210.5
18     18    210.5
19     19    209.8
20     20    208.8
21     21    209.5
22     22    213.2
23     23    213.7
24     24    215.1
25     25    218.7
26     26    219.8
27     27    220.5
28     28    223.8
29     29    222.8
30     30    223.8
31     31    221.7
32     32    222.3
33     33    220.8
34     34    219.4
35     35    220.1
36     36    220.6
37     37    218.9
38     38    217.8
39     39    217.7
40     40    215.0
41     41    215.3
42     42    215.9
43     43    216.7
44     44    216.7
45     45    217.7
46     46    218.7
47     47    222.9
48     48    224.9
49     49    222.2
50     50    220.7
51     51    220.0
52     52    218.7
53     53    217.0
54     54    215.9
55     55    215.8
56     56    214.1
57     57    212.3
58     58    213.9
59     59    214.6
60     60    213.6
61     61    212.1
62     62    211.4
63     63    213.1
64     64    212.9
65     65    213.3
66     66    211.5
67     67    212.3
68     68    213.0
69     69    211.0
70     70    210.7
71     71    210.1
72     72    211.4
73     73    210.0
74     74    209.7
75     75    208.8
76     76    208.8
77     77    208.8
78     78    210.6
79     79    211.9
80     80    212.8
81     81    212.5
82     82    214.8
83     83    215.3
84     84    217.5
85     85    218.8
86     86    220.7
87     87    222.2
88     88    226.7
89     89    228.4
90     90    233.2
91     91    235.7
92     92    237.1
93     93    240.6
94     94    243.8
95     95    245.3
96     96    246.0
97     97    246.3
98     98    247.7
99     99    247.6
100   100    247.8
101   101    249.4
102   102    249.0
103   103    249.9
104   104    250.5
105   105    251.5
106   106    249.0
107   107    247.6
108   108    248.8
109   109    250.4
110   110    250.7
111   111    253.0
112   112    253.7
113   113    255.0
114   114    256.2
115   115    256.0
116   116    257.4
117   117    260.4
118   118    260.0
119   119    261.3
120   120    260.4
121   121    261.6
122   122    260.8
123   123    259.8
124   124    259.0
125   125    258.9
126   126    257.4
127   127    257.7
128   128    257.9
129   129    257.4
130   130    257.3
131   131    257.6
132   132    258.9
133   133    257.8
134   134    257.7
135   135    257.2
136   136    257.5
137   137    256.8
138   138    257.5
139   139    257.0
140   140    257.6
141   141    257.3
142   142    257.5
143   143    259.6
144   144    261.1
145   145    262.9
146   146    263.3
147   147    262.8
148   148    261.8
149   149    262.2
150   150    262.7

In [17]:
from AutoClean import AutoClean
pipeline = AutoClean(df, mode='auto', duplicates=True, missing_num=True, missing_categ=True, 
          encode_categ=True, extract_datetime=True, outliers=True, outlier_param=1.5, 
          logfile=True, verbose=True)

21-12-2022 05:27:48.95 - INFO - Started validation of input parameters...
21-12-2022 05:27:48.95 - INFO - Completed validation of input parameters
21-12-2022 05:27:48.96 - INFO - Started handling of duplicates... Method: "AUTO"
21-12-2022 05:27:48.96 - DEBUG - 0 missing values found
21-12-2022 05:27:48.97 - INFO - Completed handling of duplicates in 0.006887 seconds
21-12-2022 05:27:48.97 - INFO - Started handling of missing values...
21-12-2022 05:27:48.97 - DEBUG - 0 missing values found
21-12-2022 05:27:48.98 - INFO - Completed handling of missing values in 0.005013 seconds
21-12-2022 05:27:48.98 - INFO - Started handling of outliers... Method: "WINZ"
21-12-2022 05:27:48.98 - INFO - Completed handling of outliers in 0.003458 seconds
21-12-2022 05:27:48.98 - INFO - Started conversion of DATETIME features... Granularity: s
21-12-2022 05:27:48.99 - INFO - Completed conversion of DATETIME features in 0.0021 seconds
21-12-2022 05:27:48.99 - INFO - Started encoding categorical features... Method: "AUTO"
21-12-2022 05:27:49.00 - INFO - Completed encoding of categorical features in 1e-06 seconds
21-12-2022 05:27:49.00 - INFO - Started feature type conversion...
21-12-2022 05:27:49.00 - DEBUG - Conversion to type INT succeeded for feature "time"
21-12-2022 05:27:49.01 - DEBUG - Conversion to type FLOAT succeeded for feature "BJsales"
21-12-2022 05:27:49.01 - INFO - Completed feature type conversion for 2 feature(s) in 0.0129 seconds
21-12-2022 05:27:49.01 - INFO - AutoClean process completed in 0.075835 seconds

Logfile saved to: /content/autoclean.log

In [18]:
pipeline.output.shape

(150, 2)